pipeline{
 agent any
 environment {
    ANYPOINT = credentials('ANYPOINT')
 }
 stage('Unit Test') { 
      steps {
        sh 'mvn clean test'
      }
    }
       stage('Deploy Standalone') { 
           steps {
             sh 'mvn deploy -P standalone'
      }
       }
 	      stage ('Deploy CLOUDHUB'){
 		           steps {
 		          	
 				     sh 'mvn -f mygitproject/pom.xml package deploy  -Dusername=$ANYPOINT_USR -Dpassword=$ANYPOINT_PSW -Denvironment=Sandbox -DmuleDeploy'
 			
 		}
 	}
 }


