pipeline{
 agent any
 environment {
    ANYPOINT = credentials('ANYPOINT')
 }
 stages {
 	stage ('Build'){
 		steps {
 			
 				sh 'mvn clean package -DskipMunitTests'
 			
 		}
 	}
 	stage ('Deploy'){
 		steps {
 			
 				sh 'mvn -f mygitproject/pom.xml package deploy  -Dusername=$ANYPOINT_USR -Dpassword=$ANYPOINT_PSW -Denvironment=Development -DmuleDeploy'
 			
 		}
 	}
 }

}
